USE SQL_CASESTUDYBASIC

--DATA PREPARATION AND UNDERSTANDING

--1.What is the total number of rows in each of the 3 tables in the database?

SELECT * FROM (
			SELECT 'CUSTOMER' AS TABLE_NAME, COUNT(*) AS NO_OF_RECORDS FROM CUSTOMER UNION ALL
			SELECT 'PROD_CAT_INFO' AS TABLE_NAME, COUNT(*) AS NO_OF_RECORDS FROM PROD_CAT_INFO UNION ALL
			SELECT 'TRANSACTIONS' AS TABLE_NAME, COUNT(*) AS NO_OF_RECORDS FROM TRANSACTIONS
			)TBL


--2.What is the total number of transactions that have return?

SELECT 
	COUNT (*) AS [TOTAL NUMBER OF RETURN]
	FROM TRANSACTIONS 
	WHERE QTY<0
	 
--4.What is the time range of the transaction data available for analysis? show the output 
--in number of days,months,and year simultaneously in different columns.

SELECT 
	DATEDIFF(DD,MIN(TRAN_DATE),MAX(TRAN_DATE)) AS [DAYS],
	DATEDIFF(MM,MIN(TRAN_DATE),MAX(TRAN_DATE)) AS [MONTHS],
	DATEDIFF(YYYY,MIN(TRAN_DATE),MAX(TRAN_DATE)) AS [YEAR]
	FROM TRANSACTIONS

--5. Which product category does the sub-category "DIY" belong to?

SELECT 
	PROD_CAT
	FROM PROD_CAT_INFO
	WHERE PROD_SUBCAT = 'DIY'

--DATA ANALYSIS

--1.Which channel is most frequently used for transactions?

SELECT TOP 1
	STORE_TYPE,
	COUNT(STORE_TYPE) AS [MOST USED]
	FROM TRANSACTIONS
	GROUP BY STORE_TYPE
	ORDER BY [MOST USED] DESC


--2.What is the count of male and female cusomers in the database?

SELECT
	COUNT (*) AS TOTAL,
	COUNT(CASE WHEN GENDER = 'M' THEN 1 END) AS [TOTAL NUMBER OF MALE],
	COUNT(CASE WHEN GENDER = 'F' THEN 1 END) AS [TOTAL NUMBER OF FEMALE]
	FROM CUSTOMER

--3.From which city do we have the maximum number of customers and how many?

SELECT TOP 1
	CITY_CODE,
	COUNT(CITY_CODE) AS [TOTAL CUSTOMER]
	FROM CUSTOMER
	GROUP BY CITY_CODE
	ORDER BY [TOTAL CUSTOMER] DESC

--4.How many sub-categories are there under the books category?

SELECT 
	PROD_CAT,
	COUNT(PROD_CAT) AS [TOTAL_SUBCAT]
	FROM PROD_CAT_INFO
	WHERE PROD_CAT = 'BOOKS'
	GROUP BY PROD_CAT


--5.What is the maximum quantity of product ever ordered?

SELECT 
	MAX(QTY) AS [MAX_QTY]
	FROM TRANSACTIONS
	
--6.What is the net total revenue generated in categories Electroics and books?

SELECT 
		PROD_CAT,
		SUM(TOTAL_AMT) AS [TOTAL REVENUE]
		FROM TRANSACTIONS
			INNER JOIN
		PROD_CAT_INFO ON PROD_CAT_INFO.prod_cat_code = TRANSACTIONS.PROD_CAT_CODE 
						AND PROD_CAT_INFO.prod_sub_cat_code = TRANSACTIONS.prod_subcat_code
		WHERE PROD_CAT = 'ELECTRONICS' OR PROD_CAT = 'BOOKS'
		GROUP BY PROD_CAT
		
		
--7.How many Customers have >10 transactions with us, excluding returns?		

SELECT 
	CUSTOMER_ID,
	COUNT(CUSTOMER_ID) AS [COUNT OF SERVICES]
	FROM CUSTOMER
		INNER JOIN
	TRANSACTIONS ON CUSTOMER.CUSTOMER_ID= TRANSACTIONS.CUST_ID
	WHERE QTY > 0
	GROUP BY CUSTOMER_ID
	HAVING COUNT(CUSTOMER_ID) > 10
	ORDER BY [COUNT OF SERVICES] DESC
	

--8.What is the combined revenue earned from the "Electroics" & "Clothing" categories,from "Flagship stores"?

SELECT 
		STORE_TYPE AS [STORE TYPE],
		SUM(TOTAL_AMT) AS [TOTAL REVENUE]
		FROM TRANSACTIONS
			INNER JOIN
		PROD_CAT_INFO ON PROD_CAT_INFO.prod_cat_code = TRANSACTIONS.PROD_CAT_CODE 
						AND PROD_CAT_INFO.prod_sub_cat_code = TRANSACTIONS.prod_subcat_code
		WHERE PROD_CAT IN ('ELECTRONICS','CLOTHING') AND STORE_TYPE = 'FLAGSHIP STORE'
		GROUP BY STORE_TYPE

		

--9.What is the total revenue generated from "MALE" customers in "Electronics" category? Output should dispaly total revenue by prod sub-cat.

SELECT 
		PROD_CAT,
		PROD_SUBCAT,
		GENDER AS [GENDER],
		SUM(TOTAL_AMT) AS [TOTAL REVENUE]
		FROM CUSTOMER
			INNER JOIN
		TRANSACTIONS ON CUSTOMER.CUSTOMER_ID = TRANSACTIONS.CUST_ID
			INNER JOIN
		PROD_CAT_INFO ON PROD_CAT_INFO.prod_cat_code = TRANSACTIONS.PROD_CAT_CODE 
						AND PROD_CAT_INFO.prod_sub_cat_code = TRANSACTIONS.prod_subcat_code
		WHERE  GENDER = 'M' AND PROD_CAT = 'ELECTRONICS' 
		GROUP BY PROD_CAT,PROD_SUBCAT,GENDER

		

--10.What is the percentage of sales and returns by product sub category; dispaly only top 5 sub categories in terms of sales?

SELECT TOP 5 
		PROD_SUBCAT, (SUM(TOTAL_AMT)/(SELECT SUM(TOTAL_AMT)AS [TOTAL REVENUE] FROM TRANSACTIONS))*100 AS PERCANTAGE_OF_SALES, 
		(COUNT(CASE WHEN QTY< 0 THEN QTY ELSE NULL END)/SUM(QTY))*100 AS PERCENTAGE_OF_RETURN
		FROM TRANSACTIONS
		INNER JOIN PROD_CAT_INFO ON PROD_CAT_INFO.prod_cat_code = TRANSACTIONS.PROD_CAT_CODE 
						AND PROD_CAT_INFO.prod_sub_cat_code = TRANSACTIONS.prod_subcat_code
		GROUP BY PROD_SUBCAT
        ORDER BY SUM(TOTAL_AMT) DESC

	

	

--11.For all customers aged between 25 to 35 years find whAt is the net total revenue generated by these consumers 
---- in last 30 days of transactions from max transaction date available in the data? 

SELECT 
	 SUM(TOTAL_AMT) AS [TOTAL REVENUE] FROM TRANSACTIONS
		WHERE CUST_ID in(
					SELECT CUST_ID FROM CUSTOMER
                    WHERE DATEDIFF(YEAR,CONVERT(DATE,DOB,103),GETDATE()) BETWEEN 25 AND 35)
                    AND CONVERT(DATE,TRAN_DATE,103) BETWEEN DATEADD(DAY,-30,(SELECT MAX(CONVERT(DATE,TRAN_DATE,103)) FROM TRANSACTIONS)) 
	                AND (SELECT MAX(CONVERT(DATE,TRAN_DATE,103)) FROM TRANSACTIONS)
		GROUP BY CUST_ID

			

--12.Which product category has seen the max value of returns in the last 3 months of tranactions?

SELECT  TOP 1
		PROD_CAT,
		SUM(TOTAL_AMT) AS VALUE
		FROM   TRANSACTIONS T1
			   INNER JOIN
			 PROD_CAT_INFO T2 ON T1.PROD_CAT_CODE = T2.prod_cat_code AND T1.PROD_SUBCAT_CODE=T2.prod_sub_cat_code
		     WHERE TOTAL_AMT > 0 
			 AND  CONVERT(DATE,TRAN_DATE,103) BETWEEN DATEADD(MONTH,-3,(SELECT MAX(CONVERT(DATE,TRAN_DATE,103)) FROM TRANSACTIONS))
	         AND (SELECT MAX(CONVERT(DATE,TRAN_DATE,103)) FROM TRANSACTIONS)
GROUP BY PROD_CAT
ORDER BY 2 DESC
		
		
--13.Which store_type sells the maximum products;by value of sales amount and by quantity sold?

SELECT TOP 1
	STORE_TYPE,
	SUM(QTY) AS [QUANTITY],
	SUM(TOTAL_AMT) AS [TOTAL AMOUNT]
	FROM TRANSACTIONS
	GROUP BY STORE_TYPE
	ORDER BY [TOTAL AMOUNT] DESC
	

--14.What are the categories for which average revenue is above the overall average?

SELECT 
		PROD_CAT,
		AVG(TOTAL_AMT) AS [TOTAL AMOUNT]
		FROM TRANSACTIONS
			INNER JOIN
		PROD_CAT_INFO ON PROD_CAT_INFO.prod_cat_code = TRANSACTIONS.PROD_CAT_CODE 
						AND PROD_CAT_INFO.prod_sub_cat_code = TRANSACTIONS.prod_subcat_code
		GROUP BY PROD_CAT
		HAVING AVG(TOTAL_AMT)> (SELECT AVG(TOTAL_AMT) AS [AVERAGE] FROM TRANSACTIONS)


	

--15.Find the average and total revenue by each subcategory for the categories which are among top 5 categories in 
---- terms of quantity sold?

SELECT 
     PROD_CAT, PROD_SUBCAT, AVG(TOTAL_AMT) AS AVERAGE_REV, SUM(TOTAL_AMT) AS REVENUE
      FROM TRANSACTIONS
		INNER JOIN
	  PROD_CAT_INFO ON PROD_CAT_INFO.prod_cat_code = TRANSACTIONS.PROD_CAT_CODE 
						AND PROD_CAT_INFO.prod_sub_cat_code = TRANSACTIONS.prod_subcat_code
      WHERE PROD_CAT IN
                 (
                  SELECT TOP 5 
					PROD_CAT
					FROM TRANSACTIONS
			        INNER JOIN
		            PROD_CAT_INFO ON PROD_CAT_INFO.prod_cat_code = TRANSACTIONS.PROD_CAT_CODE 
					AND PROD_CAT_INFO.prod_sub_cat_code = TRANSACTIONS.prod_subcat_code
					GROUP BY PROD_CAT
					ORDER BY SUM(QTY) DESC
					)
      GROUP BY PROD_CAT, PROD_SUBCAT 
